// SPDX-License-Identifier: MPL-2.0
import { join } from "node:path";
import type {
  DocumentationAccumulator,
  DocumentationContribution,
  GenerationContext,
} from "../contracts.js";
import { writeText } from "../files.js";

type OwnedDocumentation = DocumentationContribution & {
  owner: string;
};

export class DefaultDocumentationAccumulator {
  private readonly entries = new Map<string, OwnedDocumentation>();

  scoped(owner: string): DocumentationAccumulator {
    return {
      add: (contribution) => this.add(owner, contribution),
    };
  }

  add(owner: string, contribution: DocumentationContribution): void {
    const target = contribution.target ?? "root";
    const key = `${target}:${contribution.id}`;
    const existing = this.entries.get(key);
    if (!existing) {
      this.entries.set(key, { ...contribution, target, owner });
      return;
    }

    if (
      existing.title !== contribution.title
      || existing.content.trim() !== contribution.content.trim()
    ) {
      throw new Error(
        `Documentation conflict for "${contribution.id}": `
        + `${existing.owner} and ${owner} contributed different content.`,
      );
    }
  }

  async finalize(context: GenerationContext): Promise<string[]> {
    const targets = ["root", "frontend", "backend"] as const;
    const written: string[] = [];

    for (const target of targets) {
      const entries = [...this.entries.values()]
        .filter((entry) => (entry.target ?? "root") === target)
        .sort((left, right) =>
          (left.order ?? 0) - (right.order ?? 0)
          || left.id.localeCompare(right.id));
      if (entries.length === 0) continue;

      const directory = target === "root"
        ? context.rootDirectory
        : join(
          context.rootDirectory,
          target === "frontend"
            ? context.directories.frontend ?? "frontend"
            : context.directories.backend ?? "backend",
        );
      const content = [
        `# ${target === "root" ? context.projectName : `${context.projectName} ${target}`}`,
        "",
        "Generated by StackForge.",
        "",
        ...entries.flatMap((entry) => [
          `## ${entry.title}`,
          "",
          entry.content.trim(),
          "",
        ]),
      ].join("\n");

      const path = join(directory, "README.md");
      await writeText(path, "", content);
      written.push(path);
    }

    return written;
  }
}
