import { access, mkdir } from "node:fs/promises";
import { constants } from "node:fs";
import { join } from "node:path";
import { spawn } from "node:child_process";
import type {
  GenerationContext,
  GenerationEngine,
  ProviderRegistry,
  StackForgeProvider,
} from "./contracts.js";
import { writeText } from "./files.js";

export class DefaultGenerationEngine implements GenerationEngine {
  constructor(private readonly registry: ProviderRegistry) {}

  async generate(context: GenerationContext): Promise<void> {
    await this.assertTargetIsAvailable(context.rootDirectory);
    const providers = context.selection.providerIds.map((id) => {
      const provider = this.registry.get(id);
      if (!provider) throw new Error(`Unknown provider: ${id}`);
      return provider;
    });

    this.validate(providers, context);
    await mkdir(context.rootDirectory, { recursive: true });
    await this.prepareDirectories(context);

    for (const provider of providers) {
      context.log(`Generating ${provider.metadata.name}...`);
      await provider.generator.generate(context);
    }

    await this.writeSharedFiles(context);

    for (const provider of providers.flatMap((provider) => provider.postInstallHooks ?? [])) {
      context.log(`Running ${provider.name}...`);
      await provider.run(context);
    }
  }

  private validate(providers: StackForgeProvider[], context: GenerationContext): void {
    const selected = new Set(context.selection.providerIds);
    for (const provider of providers) {
      const compatibility = provider.compatibility;
      if (compatibility.projectTypes && !compatibility.projectTypes.includes(context.selection.projectType)) {
        throw new Error(`${provider.metadata.name} is not available for this project type.`);
      }
      for (const id of compatibility.requires ?? []) {
        if (!selected.has(id)) throw new Error(`${provider.metadata.name} requires ${id}.`);
      }
      for (const id of compatibility.conflictsWith ?? []) {
        if (selected.has(id)) throw new Error(`${provider.metadata.name} cannot be used with ${id}.`);
      }
      for (const rule of compatibility.rules ?? []) {
        if (!rule.isCompatible(context.selection)) throw new Error(rule.reason);
      }
    }
  }

  private async assertTargetIsAvailable(rootDirectory: string): Promise<void> {
    try {
      await access(rootDirectory, constants.F_OK);
      throw new Error(`The target directory already exists: ${rootDirectory}`);
    } catch (error) {
      if (error instanceof Error && error.message.startsWith("The target")) throw error;
    }
  }

  private async writeSharedFiles(context: GenerationContext): Promise<void> {
    const isFullStack = context.selection.projectType === "full-stack";
    const directories = isFullStack ? "- `frontend/` contains the client\n- `backend/` contains the server\n" : "";
    await Promise.all([
      writeText(context.rootDirectory, ".gitignore", "node_modules/\ndist/\n.env\n.env.local\n__pycache__/\n*.py[cod]\ntarget/\n.idea/\n.DS_Store\n"),
      writeText(context.rootDirectory, ".editorconfig", "root = true\n\n[*]\ncharset = utf-8\nend_of_line = lf\ninsert_final_newline = true\nindent_style = space\nindent_size = 2\n"),
      writeText(context.rootDirectory, "README.md", `# ${context.projectName}\n\nGenerated by StackForge.\n\n## Structure\n\n${directories}\n## Getting started\n\nSee the README files inside each generated application.\n`),
    ]);
    try {
      await access(join(context.rootDirectory, ".env.example"), constants.F_OK);
    } catch {
      await writeText(context.rootDirectory, ".env.example", "JWT_SECRET=\n");
    }
  }

  private async prepareDirectories(context: GenerationContext): Promise<void> {
    if (context.selection.projectType !== "full-stack") return;

    await Promise.all([
      mkdir(join(context.rootDirectory, context.directories.frontend ?? "frontend"), { recursive: true }),
      mkdir(join(context.rootDirectory, context.directories.backend ?? "backend"), { recursive: true }),
    ]);
  }
}

export async function runCommand(command: string, args: string[], cwd: string): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: "inherit", shell: process.platform === "win32" });
    child.once("error", reject);
    child.once("exit", (code) => code === 0 ? resolve() : reject(new Error(`${command} exited with code ${code ?? "unknown"}.`)));
  });
}

export function targetDirectory(context: GenerationContext, category: "frontend" | "backend"): string {
  if (context.selection.projectType === "full-stack") return join(context.rootDirectory, category);
  return context.rootDirectory;
}
